name: Publish Package to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Update package.json with release tag
        id: update_version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          # Strip the 'v' prefix if it exists, as npm doesn't use it.
          VERSION=${TAG#v}
          echo "Updating package.json version to $VERSION"
          npm version "$VERSION" --no-git-tag-version

      - name: Create branch for version update
        id: create_branch
        run: |
          VERSION=${{ steps.update_version.outputs.VERSION }}
          BRANCH_NAME="chore/release-version-${{ github.event.release.tag_name }}"
          echo "NEW_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b "$BRANCH_NAME"
          git add package.json package-lock.json
          git commit -m "Update package.json to version ${{ github.event.release.tag_name }}"
          git push origin "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request for version update
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update package.json to version ${{ github.event.release.tag_name }}"
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ github.event.repository.default_branch }}
          title: " chore: Update version for release ${{ github.event.release.tag_name }}"
          body: |
            This PR automatically updates the package version to match the new release tag.

      - name: Publish to npm
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
